services:
    app:
        build:
            context: .
            target: ${GO_ENV}
        env_file: "./.env"
        container_name: 'sassy-app'
        environment:
            API_DB_HOST: ${API_DB_HOST}
            API_DB_PORT: ${API_DB_PORT}
            API_DB_USER: ${API_DB_USER}
            API_DB_PASS: ${API_DB_PASS}
            API_DB_DATABASE: ${API_DB_DATABASE}
            AUTH_DB_HOST: ${AUTH_DB_HOST}
            AUTH_DB_PORT: ${AUTH_DB_PORT}
            AUTH_DB_USER: ${AUTH_DB_USER}
            AUTH_DB_PASS: ${AUTH_DB_PASS}
            AUTH_DB_DATABASE: ${AUTH_DB_DATABASE}
            API_URL: ${API_URL}
            AUTH_URL: ${AUTH_URL}
            ADMIN_URL: ${ADMIN_URL}
        ports: 
            - '7070:7070'
            - '8080:8080'
            - '9090:9090'
        volumes:
            - .:/app
        networks:
            - sassy-network

    api:
        image: "mysql:latest"
        restart: always
        env_file: "./.env"
        container_name: 'sassy-api-db'
        environment:
            MYSQL_ROOT_PASSWORD: ${API_DB_PASS}
            MYSQL_DATABASE: ${API_DB_DATABASE}
            MYSQL_USER: ${API_DB_USER}
            MYSQL_PASSWORD: ${API_DB_PASS}
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - '3306:3305'
        networks: 
            - sassy-network
            
networks:
    sassy-network:
        external: true