services:
    app:
        build:
            context: .
            target: ${GO_ENV}
        env_file: "./.env"
        container_name: 'sassy-app'
        environment:
            API_DB_HOST: ${API_DB_HOST}
            API_DB_PORT: ${API_DB_PORT}
            API_DB_USER: ${API_DB_USER}
            API_DB_PASS: ${API_DB_PASS}
            API_DB_DATABASE: ${API_DB_DATABASE}
            AUTH_DB_HOST: ${AUTH_DB_HOST}
            AUTH_DB_PORT: ${AUTH_DB_PORT}
            AUTH_DB_USER: ${AUTH_DB_USER}
            AUTH_DB_PASS: ${AUTH_DB_PASS}
            AUTH_DB_DATABASE: ${AUTH_DB_DATABASE}
            API_URL: ${API_URL}
            AUTH_URL: ${AUTH_URL}
            ADMIN_URL: ${ADMIN_URL}
        ports: 
            - '7070:7070'
            - '8080:8080'
            - '9090:9090'
        volumes:
            - .:/app